FROM swr.cn-north-4.myhuaweicloud.com/claw/scienceclaw-websearch:release-v0.0.3

WORKDIR /search

# Copy websearch source code
COPY . /search/

EXPOSE 8068

CMD ["gunicorn", "main:app", "-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0:8068", "--timeout", "120"]
